### ISSUE TITLE
Node 12+ required to run the extension locally

### ISSUE THREAD

**Issue by arnaudvalle** [sindresorhus/refined-github#3202]
Hello there,

just noticed that a recent change from https://github.com/sindresorhus/refined-github/pull/3171 is making the extension runable only on Node 12+.

I reckon this is coming from the use of [Object.fromEntries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) in `webpack.config.ts` (i.e. https://github.com/sindresorhus/refined-github/blame/fe806803b0a6cc6e473e5e10d00a00fb5571a178/webpack.config.ts#L51 or https://github.com/sindresorhus/refined-github/blame/fe806803b0a6cc6e473e5e10d00a00fb5571a178/webpack.config.ts#L98).

I couldn't see any mention of that requirement anywhere, so I wondered if it had been done on purpose? If it wasn't, maybe it's worth a note somewhere (or we could add an `engines` property in the `package.json` for example)?

**Comment by fregante** [comment]
`engine` is only read from dependencies, it doesn't affect the local package/app.

For the record, this is the full error. It appears regardless of the `engine` and honestly I don't think there's a way to suggest a node version other than just writing it on contributing.md

```
❯ npm run build

> @ build .
> run-p build:* --continue-on-error


> @ build:typescript .
> tsc --noEmit


> @ build:webpack .
> webpack --mode=production


./webpack.config.ts:51
        entry: Object.fromEntries([
               ^
TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (./webpack.config.ts:51:16)
    at Module._compile (./node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (./node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (./node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (./node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (./node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at ./node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (./node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (./node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (./node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at ./node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (./node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (./node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by busches** [comment]
We define the version we test against in CI, we could link to that in
contributing.

**Comment by fregante** [comment]
> We define the version we test against in CI

Actually we don't, we just use the default of `ubuntu-latest`, currently 12.16

**Comment by busches** [comment]
> > We define the version we test against in CI
> 
> Actually we don't, we just use the default of `ubuntu-latest`, currently 12.16

https://github.com/sindresorhus/refined-github/blob/master/.github/workflows/test.yml#L25

**Comment by fregante** [comment]
Heh, indeed, but as the comment suggests, it's only there because our tests don't run on *newer* Node versions, not because they don't run on _older_. i.e. once https://github.com/sindresorhus/refined-github/issues/2900 is fixed, that line can be removed.

**Comment by fregante** [comment]
@arnaudvalle https://github.com/sindresorhus/refined-github/issues/2900 requires Node 13 (with warnings) or Node 14 (flawless).

What can we do to close this issue?

**Comment by arnaudvalle** [comment]
> What can we do to close this issue?

To me, a simple `Requirements` section or notice somewhere on the `contributing.md` file would be enough. It's just so people who'd like to contribute don't get stuck because of that error. Maybe just before `Notions`? 

I'm happy to open up a PR if you're ok with that.
