### ISSUE TITLE
`forked-to`: Cannot set property 'href' of undefined

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#4315]
URL: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

```js
TypeError: Cannot set property 'href' of undefined
  at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6898:92)
  at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1946:18)
  at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1959:34)
```
	

When clicking history.back()

**Comment by cheap-glitch** [comment]
I can't reproduce this on Firefox with the latest RGH version.

**Comment by yakov116** [comment]
Weird I get it on one computer but not on the other. I will debug

**Comment by yakov116** [comment]
Happens if you have 2 forks (For example if you have one under your name and one under an org)
