### ISSUE TITLE
Deployment builds are failing

### ISSUE THREAD

**Issue by brycekahle** [sindresorhus/refined-github#623]
https://travis-ci.org/sindresorhus/refined-github/builds/253917298

```
> webpack
Hash: 7efb917c088b33fefd28
Version: webpack 3.2.0
Time: 436ms
        Asset     Size  Chunks             Chunk Names
   options.js  4.09 kB       0  [emitted]  options
   content.js  4.08 kB       1  [emitted]  content
background.js  4.09 kB       2  [emitted]  background
   [0] ./src/content.js 1.61 kB {1} [built] [failed] [1 error]
   [1] ./src/background.js 1.61 kB {2} [built] [failed] [1 error]
   [2] ./src/options.js 1.61 kB {0} [built] [failed] [1 error]
ERROR in ./src/content.js
Module build failed: Error: Couldn't find preset "babili" relative to directory "/home/travis/build/sindresorhus/refined-github"
    at /home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:174:20)
ERROR in ./src/background.js
Module build failed: Error: Couldn't find preset "babili" relative to directory "/home/travis/build/sindresorhus/refined-github"
    at /home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:174:20)
ERROR in ./src/options.js
Module build failed: Error: Couldn't find preset "babili" relative to directory "/home/travis/build/sindresorhus/refined-github"
    at /home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/travis/build/sindresorhus/refined-github/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/home/travis/build/sindresorhus/refined-github/node_modules/babel-loader/lib/index.js:174:20)
```

**Comment by brycekahle** [comment]
Nevermind, I see this referenced in #617

**Comment by bfred-it** [comment]
babel-preset-babili is missing, it'd great if someone can add it and test `npm run reduce-size` because I don't have time right now.
